### ISSUE TITLE
Revamping UX of the dashboard

### ISSUE THREAD

**Issue by prastut** [avisrivastava254084/zcash_service_status_dashboad#1]
Revamping UX
---

Based on the UX feedback we got from the community, plus the scope of this proposal we revamped the UX of the dashboard to make it more informative + user friendly. 

Link to the prototypes: https://www.figma.com/file/m0NhaRo5PFtCPKn86CfMTK/ZCash-Service-Status-Dashboard?node-id=23%3A0

The revamped dashboard screens look like this now:

## Landing Page Mockup

https://www.figma.com/file/m0NhaRo5PFtCPKn86CfMTK/ZCash-Service-Status-Dashboard?node-id=23%3A0
 
<br><br> 

## Exchanges Dashboard Mockup:
https://www.figma.com/file/m0NhaRo5PFtCPKn86CfMTK/ZCash-Service-Status-Dashboard?node-id=56%3A0

<br><br> 
#### Specific Trading Pair View Mockup: 
https://www.figma.com/file/m0NhaRo5PFtCPKn86CfMTK/ZCash-Service-Status-Dashboard?node-id=56%3A109

<br><br> 
#### Specific Exchange View Mockup: 
https://www.figma.com/file/m0NhaRo5PFtCPKn86CfMTK/ZCash-Service-Status-Dashboard?node-id=59%3A27

<br><br>

## Communities & Forums Dashboard Mockup: 
https://www.figma.com/file/m0NhaRo5PFtCPKn86CfMTK/ZCash-Service-Status-Dashboard?node-id=84%3A10

### Specific Website HealthCheck Details Mockup: 
https://www.figma.com/file/m0NhaRo5PFtCPKn86CfMTK/ZCash-Service-Status-Dashboard?node-id=84%3A123

## Appendix: 

Grafana plugins surveyed: 
* https://github.com/Vonage/Grafana_Status_panel/
* https://github.com/ayoungprogrammer/grafana-finance
* https://grafana.com/docs/reference/table_panel/
* https://grafana.com/docs/features/panels/singlestat/
* https://grafana.com/grafana/plugins/ryantxu-ajax-panel
* https://grafana.com/grafana/plugins/michaeldmoore-annunciator-panel

**Comment by kebab-mai-haddi** [comment]
>Landing Page Mockup

I did the best I could, unable to render it exactly as in the mockup. @prastut is the [current version](http://zcashservicestatus.info/) okay?
>Exchanges Dashboard Mockup:

Done, check [here](https://www.zcashservicestatus.info/d/n-3yUXNWk/exchanges?orgId=1)

**Comment by prastut** [comment]
Fixes: 

### Homepage: 
- [ ]  Move hompage to home dashboard as used on Statoshi
<img width="1002" alt="image" src="https://user-images.githubusercontent.com/10279686/67636315-61067580-f8f5-11e9-8d91-ffe8b63b7ade.png">

- [x] CSS Fixes in the heading panel
- [x] Spit Price Deviation in USD Panel title fix to "Spot Price Deviation of ZEC/USD Across All Exchanges"

### Exchanges Dashboard
- [x] Piecharts to have identical height. Possible solution: placing piecharts on the left, the table on the right. Eg: 
![image](https://user-images.githubusercontent.com/10279686/67636990-34a22780-f8fc-11e9-92e0-f0c058999360.png)
- [x] Trading Pairs panel title fix to "Trading Pairs Being Monitored"
- [x] Exchanges panel title fix to "Exchanges Being Monitored"
- [x] Graph change for "All Trading Pairs Transaction Volume in ZEC". Instead of table, it should be [this](https://www.figma.com/file/m0NhaRo5PFtCPKn86CfMTK/ZCash-Service-Status-Dashboard?node-id=59%3A27).

### Specific Trading Pair View: 
- [x] All 4 single value info charts in one row, the order is also important: https://www.figma.com/file/m0NhaRo5PFtCPKn86CfMTK/ZCash-Service-Status-Dashboard?node-id=56%3A109 
- [x] Title of panels to incorporate ZEC: 
   * "Average Trading volume of ZEC/BTC Across All Exchanges" 
   * "Spot Price Deviation of ZEC/BTC Across All Exchanges"
- [x] Similar to Exchanges where you have classification of panels like "Spot Price Metrics" & "Sanity Check Metrics", this has to be done for Specific Trading Pair View as well. 

<img width="940" alt="image" src="https://user-images.githubusercontent.com/10279686/67637156-96af5c80-f8fd-11e9-95a3-9c821168e70a.png">
<img width="992" alt="image" src="https://user-images.githubusercontent.com/10279686/67637163-aa5ac300-f8fd-11e9-8efa-408aa63edb41.png">



### Overall UX: 
- [ ] Title bar to reflect ZCash SSD instead of Graphana. "Exchanges - ZCash SSD"

**Comment by kebab-mai-haddi** [comment]
@prastut Unable(hard) to change the title bar and the home dashboard's zcash logo (which we discussed on call).

**Comment by kebab-mai-haddi** [comment]
@prastut Working on making the home dashboard available on the top of the expandable list.

Asking from the community.

**Comment by prastut** [comment]
Todo list: 

Classification of Panels fixes: 

> Similar to Exchanges where you have classification of panels like "Spot Price Metrics" & "Sanity Check Metrics", this has to be done for Specific Trading Pair View as well.
- [x] On ZCash Metrics Page: 
   - [x] "Transactions Type in ZCash" Classification Panel
       - [x] Transparent (T) Transactions Over Time - Heading fix + position left.
       - [x] Shielded (T) Transactions Over Time - position right.  
   -  [x] "Value Pools in ZCash" Classification Panel 
         - [x] ZCash Sprout Value Pool Over Time  - Heading fix + position left
         - [x] ZCash Sapling Value Pool Over Time  - position right
   -  [x] "Mining" Classification Panel
         - [x] ZCash Mining Difficulty Over Time

**Comment by kebab-mai-haddi** [comment]
@prastut 
I think you made changes to the home page and now it looks better. Is it good enough to be finalized? If yes, can we consider "CSS Fixes in the heading panel" as done?

**Comment by kebab-mai-haddi** [comment]
> @prastut Working on making the home dashboard available on the top of the expandable list.
> 
> Asking from the community.

@prastut I did not get much support from the communities, asked some folks who told me that you'd have to customize the Grafana. So, should we proceed to customize the Grafana template?

**Comment by prastut** [comment]
> So, should we proceed to customize the Grafana template?

@avisrivastava254084 nope, very low yield decision even to think about customizing Grafana's template.
