### ISSUE TITLE
ZCash Specific Metrics

### ISSUE THREAD

**Issue by prastut** [avisrivastava254084/zcash_service_status_dashboad#13]
## ZCash Specific Metrics

We will be graphing out the following metrics: 
 * Difficulty over time. 
 * Sprout value pool over time. 
 * Sapling value pool over time. 
 * Transparent (T) transactions over time. 
 * Shielded (Z) transactions over time.

**Comment by kebab-mai-haddi** [comment]
@prastut Can we mark this as completed?
It's done from my side.
