### ISSUE TITLE
UX Feedback on beta release of SSD Proposal 01

### ISSUE THREAD

**Issue by prastut** [avisrivastava254084/zcash_service_status_dashboad#18]
![image](https://user-images.githubusercontent.com/10279686/68447025-7b4d2700-0204-11ea-9593-b5e1169d8baf.png)

**Comment by kebab-mai-haddi** [comment]
@prastut @Lord-of-Codes 

Added this description:
https://www.zcashservicestatus.info/d/DyDEf8AZk/blockchain-explorers?orgId=1&from=1573845994229&to=1573867594229&panelId=6&fullscreen

One other thing: I think we should not add the explanation of Merkel root, etc on our dashboard given our audience base.
