### ISSUE TITLE
Extending support for communities

### ISSUE THREAD

**Issue by prastut** [avisrivastava254084/zcash_service_status_dashboad#4]
# Extending support for Communities 

**Bold** represents new additions after proposal 00:

## Websites being Monitored: 
* Communities & Forums: 
    * https://chat.zcashcommunity.com/home
    * https://forum.zcashcommunity.com/
    * https://www.zcashcommunity.com/
    * https://z.cash/
    * https://www.zfnd.org/

* **Blockchain Explorer**:
    * https://explorer.zcha.in/
    * https://zcashnetwork.info/
    * https://explorer.zcashfr.io/
    * https://explorer.zecmate.com/
    * https://chain.so/ZEC
    * https://live-sochain-blockioinc.netdna-ssl.com/zcash

## Parameters being Monitored: 
* Downtime by checking 200 status for **both** HTTP and HTTPS.
* **Response Time.**

###### Communities & Forums Overview Dashboard
We are removing Not Ok/Ok Graphs for all communities and websites. The revamped UX would look like this: 
https://www.figma.com/file/m0NhaRo5PFtCPKn86CfMTK/ZCash-Service-Status-Dashboard?node-id=84%3A10

^ On this dashboard, you will see the list of all websites we are monitoring. 

###### Specific website dashboard

User will be shown this dashboard once the user clicks on any specific website: 
https://www.figma.com/file/m0NhaRo5PFtCPKn86CfMTK/ZCash-Service-Status-Dashboard?node-id=84%3A123

**Comment by kebab-mai-haddi** [comment]
@prastut , blockchain explorers are getting monitored [here](https://www.zcashservicestatus.info/d/DyDEf8AZk/blockchain-explorers?orgId=1&from=1572778567948&to=1572800167948&panelId=2&fullscreen). Do we need this in comms and forums as well?

**Comment by prastut** [comment]
@avisrivastava254084 nope. Status check of blockchain explorers can be inside the Blockchain Explorers Dashboard.

**Comment by kebab-mai-haddi** [comment]
Considering this as completed but not yet marked it as I am waiting for the community.
@prastut

**Comment by prastut** [comment]
It can be reopened later. At the moment, issue is closed.
